### ISSUE TITLE
Doesn't work with angular.js 1.3.*

### ISSUE THREAD

**Issue by intergleam** [itsdrewmiller/angular-perfect-scrollbar#52]
How to reproduce the issue:
1) git clone 
2) open loremipsum.html and change reference to  https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js

result: error Argument 'ScrollCtrl' is not a function, got undefined

**Comment by super-coder** [comment]
OK here is the code that works with 1.3.14 
There is slight difference defining controller

<!DOCTYPE HTML>
<html>
    <head>
        <link href="../bower_components/perfect-scrollbar/min/perfect-scrollbar.min.css" rel="stylesheet">
        <!== jquery should be provided by perfect-scrollbar's bower dependencies ==>
        <script src="../bower_components/jquery/dist/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
        
        <script src="../bower_components/perfect-scrollbar/min/perfect-scrollbar.with-mousewheel.min.js" ></script>
        <script src="../src/angular-perfect-scrollbar.js" ></script>
        <style>
        	.scroller {
        		white-space: pre-line;
                height: 720px;
                width: 480px;
                overflow-y: hidden;
                position: relative;
        	}
        </style>
    </head>
<body ng-app="myApp" >
    <div ng-controller="ScrollCtrl">
        <perfect-scrollbar class="scroller" wheel-propagation="true" wheel-speed="50" refresh-on-change="someArray" on-scroll="onScroll(scrollTop, scrollHeight)">
            <button ng-click="addItem()">Add</button>
            <button ng-click="removeItem()">Remove</button>
            <div ng-repeat="times in someArray">
                {{times}}.

                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eleifend lectus et nunc congue gravida. Phasellus et iaculis risus, ut scelerisque dolor. Sed diam diam, tempor et feugiat a, pharetra sed nulla. Duis non lacinia odio, vitae ultricies dui. Ut sit amet dui quis lectus cursus laoreet et in magna. Nulla rutrum nisi urna, sit amet faucibus felis placerat ac. Cras commodo aliquam purus, eget gravida magna lacinia non. Sed facilisis, eros iaculis rhoncus adipiscing, dolor augue fermentum risus, vel vulputate massa metus ac erat.

                Pellentesque libero justo, pellentesque non neque a, ultricies eleifend lectus. Aenean a nisl mauris. Aliquam erat volutpat. Nulla et viverra nisi, sit amet venenatis leo. Quisque aliquam sed leo eu pretium. Maecenas a lobortis lacus. Aenean lacinia scelerisque aliquam. Vestibulum pretium consequat enim at lacinia. Suspendisse pretium nulla quis lacus accumsan consectetur. In hac habitasse platea dictumst.

                In risus ipsum, facilisis sit amet scelerisque imperdiet, vulputate ac erat. Quisque sed ipsum ornare, euismod quam vel, eleifend metus. Praesent ut fermentum augue. Sed sodales mollis arcu. Etiam quis erat dignissim, posuere tortor at, ullamcorper orci. Integer sodales, lectus a venenatis scelerisque, ipsum augue tempus augue, non vulputate nibh nunc ac est. Vestibulum accumsan arcu ut semper dapibus. Fusce mattis turpis et ante adipiscing, a mattis ipsum vestibulum. Aliquam non eros lobortis augue dapibus consectetur. Praesent sit amet nulla eu ligula elementum dapibus.

                Quisque id sapien vel neque malesuada cursus non dictum enim. Nam tincidunt eu ante ut imperdiet. Sed odio erat, mattis non leo eget, varius ultricies ipsum. Nulla porta est eu eros interdum dapibus. Sed a odio nisi. Sed eu vestibulum neque. Ut luctus risus nulla. Aenean dignissim porta sem, vitae dictum turpis iaculis a. Integer purus purus, dictum vitae consectetur sed, sollicitudin at enim.

                Cras sed nunc eget eros dapibus placerat. Fusce suscipit, nulla id elementum euismod, velit elit tincidunt leo, non bibendum magna nisl a diam. Donec lorem enim, tristique sed mi et, mollis luctus risus. In rutrum a magna non cursus. Duis malesuada varius elit eu hendrerit. Vivamus sed consequat augue. Proin ligula lectus, lacinia eu elementum sed, lacinia a nisi.

                Vestibulum porttitor gravida lectus vitae cursus. Sed mauris orci, aliquam in sodales vel, consectetur vitae dui. Phasellus auctor sollicitudin massa sed imperdiet. Nulla venenatis nisl molestie, consectetur metus eget, luctus lorem. Nullam blandit ut felis id consequat. Aliquam semper accumsan condimentum. Donec eu sodales mauris. Phasellus sagittis tellus sit amet purus venenatis, pellentesque convallis tellus porttitor. Etiam dictum dui nec adipiscing tincidunt. Curabitur viverra pretium est. Maecenas ligula purus, faucibus vitae mauris et, suscipit imperdiet tellus. Ut id feugiat lacus. Vivamus sed orci posuere, convallis nunc at, volutpat felis. Sed gravida libero nibh, nec mattis tortor tempus vel.
            </div>
        </perfect-scrollbar>
        <p>scrollTop:{{scrollTop}}, scrollHeight:{{scrollHeight}}</p>
    </div>
<script>
    var app = angular.module('myApp', ['perfect_scrollbar']);
    app.controller('ScrollCtrl', function ($scope) {
        $scope.someArray = [1, 2, 3];

        $scope.addItem = function () {
            var arrayLength = $scope.someArray.length;
            var nextValue = arrayLength > 0 ? $scope.someArray[arrayLength - 1] + 1 : 1;
            $scope.someArray.push(nextValue);
        };

        $scope.removeItem = function () {
            if ($scope.someArray.length) {
                $scope.someArray.pop();
            }
        }

        $scope.scrollTop = 0
        $scope.scrollHeight = 0
        $scope.onScroll = function (scrollTop, scrollHeight) {
            $scope.scrollTop = scrollTop
            $scope.scrollHeight = scrollHeight
        }

    });



</script>
</body>
</html>

**Comment by super-coder** [comment]
this plugin is dead

**Comment by KapuzenSohn** [comment]
It works under 1.4 for me

**Comment by super-coder** [comment]
well see other issues

**Comment by isherwood** [comment]
Working in the demos on AngularJS 1.6.4. Be sure to use the jQuery version for now.
